[package]
name = "stock-convert"
version = "0.2.3"
edition = "2024"

[dependencies]
iced.workspace = true
search.workspace = true
reqwest.workspace = true
tokio.workspace = true

[build-dependencies]
winres.workspace = true
